application: topcoder
version: 1
runtime: python
api_version: 1

handlers:
 
- url: /appengine_admin_media
  static_dir: appengine_admin/media

- url: /admin/?.*
  script: appadmin.py
             
- url: /media
  static_dir: media
      
- url: /.*
  script: main.py
  
